apiVersion: v1
kind: ServiceAccount
metadata:
  name: esendit-backend-sa
  namespace: esendit
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: esendit-transcode-sa
  namespace: esendit
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: esendit-delivery-sa
  namespace: esendit

