apiVersion: apps/v1
kind: Deployment
metadata:
  name: esendit-backend
  namespace: esendit
spec:
  template:
    spec:
      containers:
        - name: backend
          image: acresenditprodesendit000.azurecr.io/esendit/backend:prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esendit-worker
  namespace: esendit
spec:
  template:
    spec:
      containers:
        - name: worker
          image: acresenditprodesendit000.azurecr.io/esendit/worker:prod