apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: esendit-secrets
  namespace: esendit
spec:
  provider: azure

  secretObjects:
    - secretName: esendit-secrets
      type: Opaque
      data:
        - objectName: pg-connection-url
          key: PG_URL
        - objectName: redis-connection-url
          key: REDIS_URL

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "32a30686-7bc0-4232-9269-cc562f4be8ff"   # PROD CSI MI clientId
    keyvaultName: "kvesenditprodesendit000"
    tenantId: "7dda7dc2-fa0d-4242-a85d-16907f632abc"
    objects: |
      array:
        - |
          objectName: pg-connection-url
          objectType: secret
        - |
          objectName: redis-connection-url
          objectType: secret
